### PR TITLE
Update main.yml

### PR DESCRIPTION
**Pull request by akijumhabj**

### CODE REVIEW

**Comment by sumitsaiwal** [comment]
spam

**Comment by isaranto** [comment]
did u figure out what does it do? I got one in a repo of my one 😛

**Comment by yasandev** [comment]
@isaranto  Got one on my repo as well - Just close the pull request, cancel the workflow run & report

**Comment by Sgeo** [comment]
Got one on my repo. Looks like coin mining via Github Actions.

**Comment by RLHerbert** [comment]
[This account looks directly related](https://github.com/alkiju) so I reported them too.

**Pull request closed without merging**
